version: "2.4"
services:
  tensorflow:
    build: .
    image: fsl
    volumes:
      - ./:/fsl
      - ./data
      - ./results
      - ./summaries
    runtime: nvidia
    ports:
      - 8889:8889
    command: python main.py
