version: "2.4"
services:
  tensorflow:
    build: .
    image: fsl
    volumes:
      - ${PWD}/:/fsl
      - ${PWD}/data
      - ${PWD}/results
      - ${PWD}/summaries
      - ${PWD}/benchmark
      - ${PWD}/temp
    runtime: nvidia
    ports:
      - 8889:8889
    command: python main.py
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
