TRAIN_RECORDS = {
    "normal": {
        "normal": 67343
    },
    "probe": {
        "ipsweep": 3599,
        "nmap": 1493,
        "portsweep": 2931,
        "satan": 3633,
        "saint": 0,
        "mscan": 0,
    },
    "dos": {
        "back": 956,
        "land": 18,
        "neptune": 41214,
        "pod": 201,
        "smurf": 2646,
        "teardrop": 892,
        "apache2": 0,
        "udpstorm": 0,
        "processtable": 0,
        "mailbomb": 0,
    },
    "u2r": {
        "buffer_overflow": 30,
        "loadmodule": 9,
        "perl": 3,
        "rootkit": 10,
        "xterm": 0,
        "ps": 0,
        "sqlattack": 0,
        "httptunnel": 0,
    },
    "r2l": {
        "ftp_write": 8,
        "guess_passwd": 53,
        "imap": 11,
        "multihop": 7,
        "phf": 4,
        "spy": 2,
        "warezclient": 890,
        "warezmaster": 20,
        "snmpgetattack": 0,
        "named": 0,
        "xlock": 0,
        "xsnoop": 0,
        "sendmail": 0,
        "worm": 0,
        "snmpguess": 0,
    },
}

TEST_RECORDS = {
    "normal": {
        "normal": 9711,
    },
    "probe": {
        "ipsweep": 141,
        "nmap": 73,
        "portsweep": 157,
        "satan": 735,
        "saint": 319,
        "mscan": 996,
    },
    "dos": {
        "back": 359,
        "land": 7,
        "neptune": 4657,
        "pod": 41,
        "smurf": 665,
        "teardrop": 12,
        "apache2": 737,
        "udpstorm": 2,
        "processtable": 685,
        "mailbomb": 293,
    },
    "u2r": {
        "buffer_overflow": 20,
        "loadmodule": 2,
        "perl": 2,
        "rootkit": 13,
        "xterm": 13,
        "ps": 15,
        "sqlattack": 2,
        "httptunnel": 133,
    },
    "r2l": {
        "ftp_write": 3,
        "guess_passwd": 1231,
        "imap": 1,
        "multihop": 18,
        "phf": 2,
        "spy": 0,
        "warezclient": 0,
        "warezmaster": 944,
        "snmpgetattack": 178,
        "named": 17,
        "xlock": 9,
        "xsnoop": 4,
        "sendmail": 14,
        "worm": 2,
        "snmpguess": 331,
    }
}
